___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [2]:
import numpy as np



### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [ ]:
my_list = [5, 10, 15, 20, 25]
np.array(my_list)



array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [ ]:
np.zeros(25).reshape(5,5)



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [437]:
np.ones(16, dtype = int).reshape(4,4)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [438]:
a = np.ones(16, dtype = int).reshape(4,4)
a[::] = 7
a

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [ ]:
np.full((4,4),7)



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [ ]:
np.arange(0,17,2)



array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [ ]:
np.arange(0,25).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [3]:
from numpy.core.function_base import linspace
np.linspace(0,24, num = 25,dtype = int).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [ ]:
np.random.seed(41)
np.random.randint(5,10,5)



array([5, 8, 9, 7, 5])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [ ]:
np.random.randn(1,5,5).reshape(5,5)



array([[ 0.32244181, -1.1049976 ,  0.77786539,  1.01108918,  0.43437075],
       [ 0.48034439, -0.16192566, -1.31014743,  0.72662095,  0.38278191],
       [-1.60970499,  0.08169704,  1.52248043, -0.70863964,  1.99917033],
       [ 0.07255038, -1.8894917 ,  1.65899329,  0.81419767, -1.04872679],
       [ 0.33012382, -0.64630299,  0.1445269 ,  0.52552153, -0.55459435]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [ ]:
np.random.randint(20,50,12).reshape(4,3)



array([[49, 41, 35],
       [28, 40, 30],
       [26, 46, 21],
       [40, 34, 29]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [ ]:
ranarr = np.random.randint(50,100,48).reshape(3,16)
ranarr



array([[59, 64, 71, 63, 65, 54, 86, 79, 81, 86, 69, 98, 61, 95, 57, 76],
       [79, 97, 96, 80, 55, 90, 60, 63, 92, 68, 98, 65, 67, 89, 84, 58],
       [71, 84, 74, 67, 63, 50, 86, 83, 71, 99, 51, 97, 84, 57, 75, 60]])

In [ ]:
ranarr = np.random.randint(50,100,48).reshape(6,8)
ranarr



array([[66, 67, 59, 56, 57, 53, 85, 83],
       [77, 65, 50, 67, 51, 95, 92, 58],
       [68, 78, 57, 82, 94, 67, 71, 63],
       [93, 61, 50, 79, 64, 76, 69, 74],
       [69, 85, 83, 76, 64, 98, 92, 52],
       [81, 89, 51, 83, 67, 70, 70, 78]])

In [351]:
ranarr = np.random.randint(50,100,48).reshape(8,6)
ranarr



array([[70, 86, 98, 99, 71, 92],
       [64, 72, 55, 88, 94, 82],
       [84, 82, 66, 87, 95, 61],
       [70, 87, 68, 69, 72, 79],
       [66, 86, 77, 78, 87, 78],
       [61, 98, 66, 73, 62, 70],
       [67, 63, 76, 81, 56, 94],
       [54, 98, 57, 86, 69, 65]])

In [350]:
ranarr = np.random.randint(50,100,48).reshape(6,8)
ranarr


array([[92, 55, 58, 91, 73, 55, 55, 99],
       [82, 79, 56, 89, 54, 83, 63, 57],
       [63, 97, 93, 60, 85, 73, 64, 71],
       [72, 98, 77, 56, 81, 99, 57, 89],
       [60, 89, 77, 88, 95, 74, 62, 76],
       [89, 50, 72, 64, 77, 63, 72, 63]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [411]:
mat = np.arange(1,17).reshape(4,4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [412]:
mat[1:3,1:3]


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [413]:
mat[:,0]


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [414]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [415]:
mat[1:2,0::2]

array([[5, 7]])

### 17.Assign 77 to every cell in 3rd column.

In [416]:
mat[::,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [417]:
mat[1:2,0::2]

array([[ 5, 77]])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [418]:
mat[1::2,0::2]


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
mat



In [ ]:
mat[mat < 10]



array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
mat[mat > 12]


array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

a = mat[mat < 10]
b = mat[mat > 12]
x = a+b
x

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
x.std()



29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [419]:
# LET US REMEMBER OUR ARRAY OF "mat" 

mat



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [420]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

mat = np.arange(1,17).reshape(4,4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [421]:
mat.size


16

### 23. Get the median, mean and std of 3rd column in "mat".

In [422]:
# LET US REMEMBER OUR ARRAY OF "mat" 

mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [423]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

third_col = mat[:, 2:3]
third_col


array([[ 3],
       [ 7],
       [11],
       [15]])

In [424]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

third_row = mat[2]
third_row




array([ 9, 10, 11, 12])

In [ ]:
# LET US GET MEDIAN VALUE 

med = np.median(third_col)
med

In [426]:
# LET US GET MEAN VALUE 
mean = np.mean(third_col)
mean

9.0

In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 

std = np.std(third_col)
std


4.47213595499958

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [1]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [219]:
# LET US READ Salaries.csv 

df = pd.read_csv("Salaries.csv")
df


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS 

df.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

df.sample(2)



Id       EmployeeName                   JobTitle   BasePay  \
141731  141732  Tiffany E Perkins  Senior Telephone Operator  18596.16   
98174    98175           Tony  Yu    DA Investigative Assist  54930.30   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
141731       590.04   1347.22    205.33  20533.42          20738.75  2014   
98174          0.00      0.00  22134.29  54930.30          77064.59  2013   

        Notes         Agency  Status  
141731    NaN  San Francisco     NaN  
98174     NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

df.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
df.value_counts("Year")



Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

(df.value_counts("Year")).count()



4

In [290]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

pd.Series(df.value_counts("Year"))

Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

df["TotalPay"].max()

567595.43

In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

df["TotalPay"].mean()



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [218]:
df[(df["TotalPay"]) > (df["TotalPay"].mean())]




Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

### How much does ALBERT PARDINI make money (including benefits)?

In [255]:
df[df["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]



2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [282]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].min()]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

### What are the unique Jobs in dataset?

In [87]:
df.JobTitle.unique()


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Lieutenant (Police Department)', 'Deputy Sheriff (SFERS)',
       'Undersheriff (SFERS)'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [34]:
df["JobTitle"].value_counts().tail(3)



SENIOR GENERAL UTILITY MECHANIC    1
SPECIAL ASSISTANT XV               1
Undersheriff (SFERS)               1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [104]:
df.loc[(df.TotalPayBenefits > df.TotalPayBenefits.mean()) & (df.Year == 2012)].count()[1]


20366

### How many people have a title of Manager in their jobs?

In [111]:
df.sample()

Id   EmployeeName    JobTitle   BasePay  OvertimePay  OtherPay  \
75959  75960  Magnus J Chow  Sergeant 2  126892.0      6143.37  26586.07   

       Benefits   TotalPay  TotalPayBenefits  Year  Notes         Agency  \
75959  37754.55  159621.44         197375.99  2013    NaN  San Francisco   

       Status  
75959     NaN

In [169]:
# USE APPLY FUNCTION

def find (x):
  return df.loc[df.JobTitle.str.contains("Manager", case=False)].count()[1]

df.apply(find)[1]

4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [170]:
df.sample()

Id EmployeeName         JobTitle   BasePay  OvertimePay  OtherPay  \
132291  132292    Belle Yan  Legal Assistant  66958.41          0.0       0.0   

        Benefits  TotalPay  TotalPayBenefits  Year  Notes         Agency  \
132291  23771.19  66958.41           90729.6  2014    NaN  San Francisco   

        Status  
132291     NaN

In [174]:
as_new = df.iloc[::,[0,1,2,7,8]]
as_new


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [175]:
df.sample()

Id  EmployeeName          JobTitle   BasePay  OvertimePay  OtherPay  \
19858  19859  SARA PAREDES  REGISTERED NURSE  62331.01          0.0    1325.0   

       Benefits  TotalPay  TotalPayBenefits  Year  Notes         Agency  \
19858       NaN  63656.01          63656.01  2011    NaN  San Francisco   

       Status  
19858     NaN

In [183]:
df.loc[:,["EmployeeName","JobTitle","TotalPay","TotalPayBenefits"]]



EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [188]:
df.loc[(df.TotalPayBenefits < df.TotalPayBenefits.mean()) & (df.TotalPayBenefits > df.TotalPayBenefits.min())][["EmployeeName","TotalPayBenefits"]]



EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________